# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  # adapter: sqlite3  #old
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  # database: db/development.sqlite3 #old
  database: flatiron_mod3_development

test:
  <<: *default
  # database: db/test.sqlite3  #old
  database: flatiron_mod3_test

production:
  <<: *default
  # database: db/production.sqlite3  #old
  database: flatiron_mod3_production
