# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fa7a9903f58af8625fcca180c4b7140d8bad1da2ec40caa4d80f9ea164147c91510544401a1c52004704b9dfe271cd4c00b941496d26d2cff7a34c2fcade0222

test:
  secret_key_base: 2d140abca418e127cef2d13a7e2266324d600978a3383f53848628ec4bd5afab07cd6a9a05e71be4b8f6bd4fc261aca2616ce027248388499e4f11d67643392f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
