User.create(name: "Flex Smith", username: "funkmasterflex")
User.create(name: "Carson Daily", username: "carsonwashere")
User.create(name: "Terrance Bak", username: "chicagocubber")
User.create(name: "Chuck Wonz", username: "loverofpizza")
User.create(name: "Kanye West", username: "alltheclothes")
